name: haven
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  camera:
  fluttertoast:
  image_picker: ^1.0.4
  http:
  auto_size_text:

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/haven.svg
    - assets/images/haven_white.svg
    - assets/images/mypage.svg
    - assets/images/face.svg
    - assets/images/logcat.svg
    - assets/images/ai_logo.svg
    - assets/images/select.svg
    - assets/images/back_button.svg
    - assets/images/close_button.svg
    - assets/images/divider.svg
    - assets/images/question.svg
    - assets/images/eye_off.svg
    - assets/images/eye_on.svg
    - assets/images/pw_correct.svg
    - assets/images/pw_incorrect.svg
    - assets/images/check_icon.svg

  fonts:
    - family: Aclonica
      fonts:
        - asset: assets/font/Aclonica-Regular.ttf
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Bold.otf
          weight: 700
        - asset: assets/font/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/Pretendard-Regular.otf
          weight: 400
